### ISSUE TITLE
Brightness support

### ISSUE THREAD

**Issue by reivilibre** [smart-leds-rs/apa102-spi-rs#11]
It was a shame to see that this library doesn't support setting the brightness of the LEDs; for my application I would appreciate it but I gather from the comments that this is an intentional omission because it didn't fit in with your application :).

I'd be happy to PR support for this, but I'm not sure how brightness fits in to the `smart_leds_trait` crate either.
It seems to have an `RGBA` colour type but I don't know if alpha truly corresponds to brightness...?
What would you accept?

Ultimately I can just run a fork with brightness support shoved in, but it would be nice to not fragment the system too much so that the next person who is happy to see an APA102 crate already exists won't find this feature missing :).

**Comment by sajattack** [comment]
https://github.com/smart-leds-rs/smart-leds/blob/b5cf6f0a8770b11a35a6589218916e0ac05c6f6d/src/lib.rs#L26

**Comment by sajattack** [comment]
Add smart-leds to Cargo.toml and use the brightness iterator function as part of the write, like so
`apa102.write(brightness(data.iter().cloned(), 32)).unwrap();`

**Comment by sajattack** [comment]
Sample for ws2812, apa102 would be similar https://github.com/smart-leds-rs/smart-leds-samples/blob/53bfc6bfe4f49391f7d2f58db83b900a81ee4ace/cpx-examples/examples/cpx_ws2812_spi_pre_rainbow.rs#L66

**Comment by reivilibre** [comment]
> https://github.com/smart-leds-rs/smart-leds/blob/b5cf6f0a8770b11a35a6589218916e0ac05c6f6d/src/lib.rs#L26

Thanks for digging that up! I note that it just seems to be dividing the RGB values rather than using the 5-bit brightness field in the protocol.
I guess it's specific to APA102 and isn't available in some other RGB leds so I can see why it's not the best to build in to a generic API.
Reading more, it sounds like there are potential flickering issues because the PWM cycles of the brightness and the RGB interact, so it may be good to avoid anyway.
