### ISSUE TITLE
Off-by-one error

### ISSUE THREAD

**Issue by bestouff** [smart-leds-rs/apa102-spi-rs#9]
Hi,

I have a led strip with 72 apa102, and I have to initialize an array with 73 colors to have the last one light up.
Either there's an off-by-one error somewhere, or the trailing frames are wrong.

**Comment by niclashoyer** [comment]
Are you sure they are APA102? There seems to be a difference between APA102 and SK9822 (clones) that update *on the next start frame* instead updating immediately. A possible fix is described here: https://cpldcpu.wordpress.com/2016/12/13/sk9822-a-clone-of-the-apa102/

The driver needs to send another 32 zeros as "end frame".

**Comment by niclashoyer** [comment]
According to https://github.com/smart-leds-rs/apa102-spi-rs/issues/1#issuecomment-532835445 `invert_postamble` could do the trick
